#define CMD_MCU_RESET_ENCODER 1
#define CMD_MCU_SET_PWM 2
#define CMD_MCU_LIDAR_MOTOR_ON 3
#define CMD_MCU_LIDAR_MOTOR_OFF 4
#define CMD_MCU_SET_MOTION 5
#define CMD_MCU_SET_VEL 6
#define CMD_DEBUG_ON 100
#define CMD_DEBUG_OFF 99

